### ISSUE TITLE
Path Marker not available anymore in RuneLite

### ISSUE THREAD

**Issue by CypherNL** [GeChallengeM/path-marker#1]
Since today, i don't see the Path Marker plugin installed anymore. Also it's not available in the plugin hub in RuneLite as on the RuneLite website.

**Comment by allsfall** [comment]
Experiencing same issue.

**Comment by sn0rlacks** [comment]
Same thing here, I know it will be addressed with haste <3

**Comment by GeChallengeM** [comment]
It seems like RuneLite did a typo fix, PLAYER_EIGTH_OPTION --> PLAYER_EIGHTH_OPTION. Since this plugin still had that typo, RuneLite stopped recognising that value. Updating it now.

**Comment by GeChallengeM** [comment]
The bugfix has been merged, the plugin should work again now. You may have to restart your client first though.

**Comment by sn0rlacks** [comment]
@GeChallengeM thanks! I felt like a drug addict without this guy. 4 days without a merge from rl was savage!
