### ISSUE TITLE
Dot markers display extremely low in certain areas

### ISSUE THREAD

**Issue by LightSnowyRoad** [GeChallengeM/path-marker#12]
Barrows crypts (not the big door maze) is one example where this happens.
Tile styled markers are not affected by this, only Dot style.

Edit: Slepe Dungeon exhibits this same behavior too.

**Comment by pnobbe** [comment]
Hallowed Sepulchre also has this issue.

**Comment by GeChallengeM** [comment]
The fix is now live. Reload your client for the latest plugin version.
