### ISSUE TITLE
Need RL compatibility update

### ISSUE THREAD

**Issue by HOTP0T** [GeChallengeM/path-marker#13]
RuneLite error message : Plugin is incompatible and requires author to update
![CleanShot 2024-05-23 at 14 25 09@2x](https://github.com/GeChallengeM/path-marker/assets/137529639/f1529f3c-167f-416e-90a4-57113b4530b7)

**Comment by GeChallengeM** [comment]
I've made a pull request with the fix: https://github.com/runelite/plugin-hub/pull/6058
Once the pull request has been accepted, reload your client and it should be fixed.

**Comment by GeChallengeM** [comment]
The pull request has been merged: https://github.com/runelite/plugin-hub/pull/6058
Restart your client to get the updated plugin version.
