### ISSUE TITLE
Option to highlight tile by outline only

### ISSUE THREAD

**Issue by Gollum69** [GeChallengeM/path-marker#2]
It would be nice if we could see the path just on the outline of tiles as colouring the whole tile means it will generally have to be a very low opacity, and subsequently blends in too much with different floorings in different areas. 
An option to have it show on the outline would allow the choice of a more solid colour, making it much more visible and better looking in my opinion

**Comment by GoofyCode** [comment]
i second this

**Comment by N19htfox** [comment]
I've taken the liberty of implementing a fix in my fork and submitted a pull request
https://github.com/GeChallengeM/path-marker/pull/5

Here's a screenshot of what I came up with:
![image](https://user-images.githubusercontent.com/125593124/219564515-7e1dfc27-d766-4d33-9398-b7182b8f0418.png)

**Comment by GeChallengeM** [comment]
The above update has been merged. It'll be available through RuneLite plugin hub after it gets reviewed by a RuneLite dev.

**Comment by Gollum69** [comment]
i love runelite and i love u
